### PR TITLE
Addition Operation

### PR DESCRIPTION
**Pull request by DhruvSrikanth**
**[C]**
- Element-wise addition operation in `Tensor` class
- Support for tensor-tensor addition
- 1D tensor lengths must match
- Support for `float`

**[Python]**
- Element-wise addition in `Tensor` class (using C lib)
- Support for tensor-tensor addition and tensor-scalar addition
- Support for `float` and `int`

**[Tests]**
- Length mismatch test
- tensor-tensor addition test
- tensor-scalar addition test

### CODE REVIEW

**Comment by DhruvSrikanth** [comment]
@karpathy Interested to hear if there are any efficiency improvements to bring this closer to addition for large scale tensors...maybe some memory management tricks etc.

**Comment by karpathy** [comment]
So I think this is a nice attempt on `add`. I'm thinking that the C code itself should probably support broadcasting, and also it should probably be able to add a float natively? Basically we want the python code to be as close to pass through as possible without doing too much heavy lifting, otherwise we don't have a nice independent useful C library.

**Comment by karpathy** [comment]
see https://github.com/EurekaLabsAI/tensor/pull/9 for what i had in mind lmk any comments

**Comment by DhruvSrikanth** [comment]
Will do! I agree. I'll ensure that future additions include almost if not all functionality in C to maximizes the c-libs usability independent of Python.

**Comment by DhruvSrikanth** [comment]
This may not be the place to ask but I've developed an ndim implementation of `tensor`. Can I open a PR or should I wait till the repo moves from tensor1d to tensor2d?

**Pull request closed without merging**
